source ~/.zshenv

# User configuration
source $ZSH/oh-my-zsh.sh
source $HOME/src/z/z.sh

export NPM_AUTH_TOKEN=`sed 's/^.*=//' ~/.npmrc`

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias ctags="`brew --prefix`/bin/ctags"

set -o vi

function bk {
 baxter kumo $@
}

function be {
 bundle exec $@
}

function gs {
 git status $@
}

function nprod {
  kubectl config use-context kubernetes-staging
  export $(cat ~/.kumo/non-production-creds | xargs) && $@
}

function prod {
  kubectl config use-context kubernetes-production
  export $(cat ~/.kumo/production-creds | xargs)  && $@
}

alias emacs='/Applications/Emacs.app/Contents/MacOS/Emacs'
alias emacsclient='/Applications/Emacs.app/Contents/MacOS/bin/emacsclient'
alias ed='emacs --daemon'
alias edk='emacsclient -e "(kill-emacs)"'
function ec() {
  emacsclient -tty -c -a "" "$@"
}
function ew() {
  emacsclient -c -a "" "$@" &!
}
function v {
    vim $@
}

alias cppassword="grep password /Users/craigread/src/redbubble/config/deploy.rb | awk -F\\\" '{print \$2}' | pbcopy"
alias rake='noglob rake'
alias zeus='noglob zeus'

function cleanup_docker_images {
  # Delete all containers
  docker rm $(docker ps -a -q)
  # Delete all images
  docker rmi $(docker images -q)
}
