# source ~/.zshenv

# User configuration
source $ZSH/oh-my-zsh.sh
source $HOME/src/z/z.sh

export NPM_AUTH_TOKEN=`sed 's/^.*=//' ~/.npmrc`
export FASTLANE_USER=craig.read@redbubble.com
export REDBUBBLE_DB_PASSWORD=
export ERL_AFLAGS="-kernel shell_history enabled"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias ctags="`brew --prefix`/bin/ctags"

set -o vi

function bk {
 baxter kumo $@
}

function be {
 bundle exec $@
}

function gs {
 git status $@
}

function staging-us-east-1 {
	export $(yak staging)
	export AWS_DEFAULT_REGION=us-east-1
	kubectl config use-context staging-us-east-1 && $@
}

function staging-us-west-2 {
	export $(yak staging)
	export AWS_DEFAULT_REGION=us-west-2
	kubectl config use-context staging-us-west-2 && $@
}

function production-us-east-1 {
	export $(yak production)
	export AWS_DEFAULT_REGION=us-east-1
	kubectl config use-context production-us-east-1 && $@
}

function production-us-west-2 {
	export $(yak production)
	export AWS_DEFAULT_REGION=us-west-2
	kubectl config use-context production-us-west-2 && $@
}

function prod {
  kubectl config use-context production-us-east-1
  export $(cat ~/.kumo/production-creds | xargs)  && $@
}

# alias emacs='/Applications/Emacs.app/Contents/MacOS/Emacs'
# alias emacsclient='/Applications/Emacs.app/Contents/MacOS/bin/emacsclient'
# alias ed='emacs --daemon'
# alias edk='emacsclient -e "(kill-emacs)"'
function ec() {
  emacsclient -tty -c -a "" "$@"
}
function ew() {
  emacsclient -c -a "" "$@" &!
}
function v {
    vim $@
}

alias cppassword="grep password /Users/craigread/src/redbubble/config/deploy.rb | awk -F\\\" '{print \$2}' | pbcopy"
#alias rake='noglob rake'
#alias zeus='noglob zeus'

function cleanup_docker_images {
  # Delete all containers
  docker rm $(docker ps -a -q)
  # Delete all images
  docker rmi $(docker images -q)
}

. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash
. $HOME/.asdf/installs/rust/1.36.0/env

autoload -U colors; colors
. $HOME/.oh-my-zsh/custom/plugins/zsh-kubectl-prompt/kubectl.zsh
RPROMPT='%{$fg[yellow]%}($ZSH_KUBECTL_PROMPT)%{$reset_color%}'
